"""Recreate db

Revision ID: d28a556fccfb
Revises: 84d2bb1b693d
Create Date: 2025-10-08 16:49:43.480502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd28a556fccfb'
down_revision: Union[str, Sequence[str], None] = '84d2bb1b693d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=10), nullable=False),
    sa.Column('source_content', sa.Text(), nullable=False),
    sa.Column('generation_params', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_sets_id'), 'test_sets', ['id'], unique=False)
    op.create_table('test_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_set_id', sa.Integer(), nullable=False),
    sa.Column('front_side', sa.Text(), nullable=False),
    sa.Column('back_side', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['test_set_id'], ['test_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cards_id'), 'test_cards', ['id'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('scored_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['test_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_id'), 'scores', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_test_cards_id'), table_name='test_cards')
    op.drop_table('test_cards')
    op.drop_index(op.f('ix_test_sets_id'), table_name='test_sets')
    op.drop_table('test_sets')
    # ### end Alembic commands ###
